//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaamenProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public int id { get; set; }
        public int CustomerId { get; set; }
        public int Staffid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
